# Generated by Django 4.0.1 on 2023-12-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_task_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='createdTask',
            field=models.ManyToManyField(related_name='createdTask', to='task.Tasks'),
        ),
    ]
