# Generated by Django 4.0.1 on 2024-01-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_users_createdtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task',
            new_name='task_info',
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('pending', 'Pending')], default='created', max_length=20),
        ),
    ]
