# Generated by Django 4.0.5 on 2022-06-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='liked_users',
            field=models.ManyToManyField(related_name='users_liked', to='books_authors_app.users'),
        ),
    ]
