# Generated by Django 4.0.1 on 2023-08-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='favMovie',
            field=models.CharField(default='null', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='profilePicture',
            field=models.ImageField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
    ]
